<?php
class NCA_Publisher {
    public function publish( $article, $draft_only = true ) {
        $post_data = array(
            "post_title"    => $article["title"],
            "post_content"  => $article["content"],
            "post_excerpt"  => $article["excerpt"],
            "post_status"   => $draft_only ? "draft" : "publish",
            "post_author"   => 1,
            "tags_input"    => $article["tags"],
        );

        $post_id = wp_insert_post( $post_data );

        if ( is_wp_error( $post_id ) ) {
            return array( "success" => false, "error" => $post_id->get_error_message() );
        }

        // Flag this post as generated by AI
        update_post_meta( $post_id, "_NCA_generated", "1" );

        if ( ! empty( $article["metadata"]["META_DESCRIPTION"] ) ) {
            $desc = $article["metadata"]["META_DESCRIPTION"];
            update_post_meta( $post_id, "_NCA_meta_description", $desc );
            update_post_meta( $post_id, "_yoast_wpseo_metadesc", $desc ); 
            update_post_meta( $post_id, "rank_math_description", $desc ); 
            update_post_meta( $post_id, "_aioseop_description", $desc );  
        }
        
        if ( ! empty( $article["metadata"]["FOCUS_KEYWORDS"] ) ) {
            $kw = $article["metadata"]["FOCUS_KEYWORDS"];
            update_post_meta( $post_id, "_NCA_focus_keywords", $kw );
            update_post_meta( $post_id, "_yoast_wpseo_focuskw", $kw ); 
            update_post_meta( $post_id, "rank_math_focus_keyword", $kw ); 
        }
        
        if ( ! empty( $article["title"] ) ) {
            $seo_title_format = $article["title"] . " - " . get_bloginfo( "name" );
            update_post_meta( $post_id, "_NCA_seo_title", $seo_title_format );
            update_post_meta( $post_id, "_yoast_wpseo_title", $article["title"] . " %%page%% %%sep%% %%sitename%%" );
            update_post_meta( $post_id, "rank_math_title", $article["title"] . " %page% %sep% %sitename%" );
        }

        if ( ! empty( $article["featured_image_url"] ) ) {
            require_once( ABSPATH . "wp-admin/includes/media.php" );
            require_once( ABSPATH . "wp-admin/includes/file.php" );
            require_once( ABSPATH . "wp-admin/includes/image.php" );
            
            $image_id = media_sideload_image( $article["featured_image_url"], $post_id, $article["title"], "id" );
            
            if ( ! is_wp_error( $image_id ) ) {
                set_post_thumbnail( $post_id, $image_id );
                // Flag image as AI generated too
                update_post_meta( $image_id, "_NCA_generated", "1" );
            }
        }
        
        return array( 
            "success" => true, 
            "post_id" => $post_id, 
            "url" => get_permalink( $post_id ) 
        );
    }
}

