import os
with open("wp_content_engine.py", "r", encoding="utf-8") as f:
    code = f.read()

# 1. Add imports
import_search = "import time"
import_replace = "import time\nimport io\nfrom PIL import Image"
if "from PIL import Image" not in code:
    code = code.replace(import_search, import_replace)

# 2. Update ContentGenerator.generate_featured_image
img_gen_search = """    def generate_featured_image(self, title: str) -> str:
        if "openai" not in self.clients:
            return None
        logger.info(f"Generating featured image for: {title}")
        try:
            resp = self.clients["openai"].images.generate(
                model="dall-e-3",
                prompt=f"A modern, high-quality, professional editorial illustration representing the news headline: '{title}'. The style should be corporate, clean, and engaging. No text in the image.",
                size="1024x1024",
                quality="standard",
                n=1,
            )
            return resp.data[0].url
        except Exception as e:
            logger.warning(f"Failed to generate featured image: {e}")
            return None"""

img_gen_replace = """    def generate_featured_image(self, prompt: str, slug: str) -> str:
        if "gemini" not in self.clients:
            logger.warning("Gemini client not initialized. Cannot generate image.")
            return None
            
        logger.info(f"Generating featured image with Gemini for prompt: {prompt}")
        try:
            from google import genai
            client = self.clients["gemini"]
            result = client.models.generate_images(
                model='imagen-3.0-generate-001',
                prompt=prompt,
                config=genai.types.GenerateImagesConfig(
                    number_of_images=1,
                    output_mime_type="image/jpeg",
                    aspect_ratio="16:9"
                )
            )
            
            if not result.generated_images:
                raise ValueError("No image generated by Gemini")
                
            image_bytes = result.generated_images[0].image.image_bytes
            
            # Process with Pillow
            img = Image.open(io.BytesIO(image_bytes))
            
            # Strip EXIF by removing exif property and saving clean
            data = list(img.getdata())
            img_without_exif = Image.new(img.mode, img.size)
            img_without_exif.putdata(data)
            
            os.makedirs("drafts", exist_ok=True)
            safe_slug = slug if slug else f"image_{int(time.time())}"
            filepath = f"drafts/{safe_slug}.webp"
            
            img_without_exif.save(filepath, format="WEBP", quality=85)
            logger.info(f"Image saved locally to {filepath}")
            return filepath
            
        except Exception as e:
            logger.warning(f"Failed to generate featured image with Gemini: {e}")
            return None"""
code = code.replace(img_gen_search, img_gen_replace)

# 3. Update prompt in generate_article
prompt_search = """    def generate_article(self, config: ContentConfig, keyword_angle: str, related_posts: List[Dict], source_text: str = "") -> str:
        \"\"\"Generate a complete article tailored to the niche\"\"\"
        
        internal_links_str = "\\n".join([f"- [{p['title']}]({p['url']})" for p in related_posts]) if related_posts else "None"
        prompt = f\"\"\"You are a professional business journalist writing for an international news platform covering {config.niche}.

The specific topic/angle for this article is: {keyword_angle}

You must synthesize the following source material to write a comprehensive, original news article. Cross-check facts and cite the sources naturally.

SOURCE MATERIAL:
{source_text[:15000]}

You must include natural internal links to the following related articles on our site:
{internal_links_str}

Format the article strictly using the following structure:

---
HEADLINE: <The main headline>
SUBTITLE: <A compelling subtitle>
META_DESCRIPTION: <150-160 character SEO meta description>
FOCUS_KEYWORDS: <Comma separated list of focus keywords>
CATEGORIES: <Comma separated list of 3 relevant categories>
TAGS: <Comma separated list of relevant tags>
TWITTER_POST: <An engaging, viral tweet summarizing the article (max 280 chars) including the hashtag #news>
LINKEDIN_POST: <A professional, engaging LinkedIn post summarizing the article, including relevant hashtags>
---

<Start writing the main article content here using markdown formatting (H2, H3, bullet points).>
\"\"\"
        return prompt"""

prompt_replace = """    def generate_article(self, config: ContentConfig, keyword_angle: str, related_posts: List[Dict], source_text: str = "") -> str:
        \"\"\"Generate a complete article tailored to the niche in Nepali\"\"\"
        
        internal_links_str = "\\n".join([f"- [{p['title']}]({p['url']})" for p in related_posts]) if related_posts else "None"
        prompt = f\"\"\"You are a professional journalist writing for a Nepali news platform covering {config.niche}.

The specific topic/angle for this article is: {keyword_angle}

You must synthesize the following source material and completely REWRITE the article in Nepali to avoid any plagiarism. 
Do not directly translate sentence-by-sentence; re-structure the narrative naturally for a Nepali audience.
Cross-check facts and cite the sources naturally in the text.

SOURCE MATERIAL:
{source_text[:15000]}

You must include natural internal links to the following related articles on our site:
{internal_links_str}

Format the article strictly using the following structure:

---
HEADLINE: <The main headline in Nepali>
SUBTITLE: <A compelling subtitle in Nepali>
URL_SLUG: <English URL slug for SEO optimization (e.g. apple-new-iphone-release)>
META_DESCRIPTION: <150-160 character SEO meta description in Nepali>
FOCUS_KEYWORDS: <Comma separated list of focus keywords (mix of English and Nepali)>
CATEGORIES: <Comma separated list of 1-3 categories. YOU MUST CHOOSE ONLY FROM THIS EXACT LIST: टेक न्युज, ग्याजेट्स, एप्स र सफ्टवेयर, टेलिकम, स्टार्टअप, ए.आई>
TAGS: <Comma separated list of relevant tags in Nepali>
IMAGE_PROMPT: <Highly detailed prompt in English for an AI image generator to create the featured image. No text in the image.>
TWITTER_POST: <An engaging, viral tweet summarizing the article (max 280 chars) in Nepali including the hashtag #news>
LINKEDIN_POST: <A professional, engaging LinkedIn post summarizing the article in Nepali, including relevant hashtags>
---

<Start writing the main article content here in Nepali using markdown formatting (H2, H3, bullet points).>
\"\"\"
        return prompt"""
code = code.replace(prompt_search, prompt_replace)

# 4. Update Engine image calling
engine_search = """            # Generate image
            image_url = self.generator.generate_featured_image(article.title)
            if image_url:
                article.metadata["featured_image_url"] = image_url"""

engine_replace = """            # Generate image
            image_prompt = article.metadata.get("image_prompt", "")
            url_slug = article.metadata.get("url_slug", "post")
            if image_prompt:
                image_filepath = self.generator.generate_featured_image(image_prompt, url_slug)
                if image_filepath:
                    article.metadata["featured_image_url"] = image_filepath"""
code = code.replace(engine_search, engine_replace)


# 5. Update _upload_image
upload_search = """    def _upload_image(self, image_url: str) -> Optional[int]:
        \"\"\"Download image and upload to WordPress media library\"\"\"
        try:
            # Download image
            img_resp = requests.get(image_url, timeout=10)
            img_resp.raise_for_status()
            
            # Upload to WordPress
            files = {"file": ("featured.jpg", img_resp.content, "image/jpeg")}
            endpoint = f"{self.config.rest_api_url}/media"
            resp = requests.post(endpoint, files=files, auth=self.session.auth, timeout=30)
            resp.raise_for_status()
            
            return resp.json()["id"]
        except Exception as e:
            logger.warning(f"Image upload failed: {e}")
            return None"""

upload_replace = """    def _upload_image(self, filepath: str, slug: str) -> Optional[int]:
        \"\"\"Upload a local image file to WordPress media library\"\"\"
        try:
            filename = f"{slug}.webp" if slug else "featured.webp"
            with open(filepath, "rb") as f:
                img_data = f.read()
                
            files = {"file": (filename, img_data, "image/webp")}
            endpoint = f"{self.config.rest_api_url}/media"
            resp = requests.post(endpoint, files=files, auth=self.session.auth, timeout=30)
            resp.raise_for_status()
            
            return resp.json()["id"]
        except Exception as e:
            logger.warning(f"Image upload failed: {e}")
            return None"""
code = code.replace(upload_search, upload_replace)


# 6. Update publish call
publish_search = """        # Upload featured image if provided
        media_id = None
        if article.metadata.get("featured_image_url"):
            media_id = self._upload_image(article.metadata["featured_image_url"])"""

publish_replace = """        # Upload featured image if provided (now it's a local file path)
        media_id = None
        if article.metadata.get("featured_image_url"):
            media_id = self._upload_image(article.metadata["featured_image_url"], article.metadata.get("url_slug", "image"))"""
code = code.replace(publish_search, publish_replace)

with open("wp_content_engine.py", "w", encoding="utf-8") as f:
    f.write(code)
print("Applied Python patch")
